# API GATEWAY - PORT 8080

### Auth register via Gateway
POST http://localhost:8080/auth/api/auth/register
Content-Type: application/json

{
  "username": "fatih",
  "email": "fatih@example.com",
  "password": "123456"
}

### Auth login via Gateway
POST http://localhost:8080/auth/api/auth/login
Content-Type: application/json

{
  "email": "fatih@example.com",
  "password": "123456"
}

### Products via Gateway
GET http://localhost:8080/api/products

### Get product by id via Gateway
GET http://localhost:8080/api/products/1

### Create product via Gateway (login required)
POST http://localhost:8080/api/products
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "name": "Laptop",
  "price": 1500
}

### Categories via Gateway
GET http://localhost:8080/api/categories

### Logs via Gateway
GET http://localhost:8080/logs/api/logs
