### Register
POST http://localhost:5072/api/auth/register
Content-Type: application/json

{
  "username": "fatih",
  "email": "fatih@example.com",
  "password": "123456"
}

### Login
POST http://localhost:5072/api/auth/login
Content-Type: application/json

{
  "email": "fatih@example.com",
  "password": "123456"
}

# SWAGGER UI
### Swagger UI
GET http://localhost:5072/swagger
